email: evan.roberts@kellogg.ox.ac.uk
github: evanr70
location-or-company: University of Oxford
name: Evan Roberts
nav-items:
- Posts
- Research
- Projects
occupation: DPhil Student
photo: assets/me.png
twitter: evanr70
